# Generated by Django 3.2.4 on 2022-01-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
