# Generated by Django 3.2.4 on 2022-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applink', '0002_applink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applink',
            name='name',
            field=models.CharField(default=False, max_length=16),
        ),
    ]
