# Generated by Django 3.2.4 on 2022-01-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applink', '0003_alter_applink_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppLink',
        ),
    ]
